package org.nihongo.mochi.domain.kana

import kotlinx.serialization.json.Json

object KanaRepository {
    
    private val json = Json { ignoreUnknownKeys = true }

    fun getKanaEntries(type: KanaType): List<KanaEntry> {
        val jsonString = when (type) {
            KanaType.HIRAGANA -> HIRAGANA_JSON
            KanaType.KATAKANA -> KATAKANA_JSON
        }
        return try {
            json.decodeFromString<KanaData>(jsonString).characters
        } catch (e: Exception) {
            println("Error parsing kana data: ${e.message}")
            emptyList()
        }
    }

    private const val HIRAGANA_JSON = """
{
  "characters": [
    {"character": "あ", "romaji": "a", "type": "HIRAGANA", "line": 1},
    {"character": "い", "romaji": "i", "type": "HIRAGANA", "line": 1},
    {"character": "う", "romaji": "u", "type": "HIRAGANA", "line": 1},
    {"character": "え", "romaji": "e", "type": "HIRAGANA", "line": 1},
    {"character": "お", "romaji": "o", "type": "HIRAGANA", "line": 1},
    {"character": "か", "romaji": "ka", "type": "HIRAGANA", "line": 2},
    {"character": "き", "romaji": "ki", "type": "HIRAGANA", "line": 2},
    {"character": "く", "romaji": "ku", "type": "HIRAGANA", "line": 2},
    {"character": "け", "romaji": "ke", "type": "HIRAGANA", "line": 2},
    {"character": "こ", "romaji": "ko", "type": "HIRAGANA", "line": 2},
    {"character": "さ", "romaji": "sa", "type": "HIRAGANA", "line": 3},
    {"character": "し", "romaji": "shi", "type": "HIRAGANA", "line": 3},
    {"character": "す", "romaji": "su", "type": "HIRAGANA", "line": 3},
    {"character": "せ", "romaji": "se", "type": "HIRAGANA", "line": 3},
    {"character": "そ", "romaji": "so", "type": "HIRAGANA", "line": 3},
    {"character": "た", "romaji": "ta", "type": "HIRAGANA", "line": 4},
    {"character": "ち", "romaji": "chi", "type": "HIRAGANA", "line": 4},
    {"character": "つ", "romaji": "tsu", "type": "HIRAGANA", "line": 4},
    {"character": "て", "romaji": "te", "type": "HIRAGANA", "line": 4},
    {"character": "と", "romaji": "to", "type": "HIRAGANA", "line": 4},
    {"character": "な", "romaji": "na", "type": "HIRAGANA", "line": 5},
    {"character": "に", "romaji": "ni", "type": "HIRAGANA", "line": 5},
    {"character": "ぬ", "romaji": "nu", "type": "HIRAGANA", "line": 5},
    {"character": "ね", "romaji": "ne", "type": "HIRAGANA", "line": 5},
    {"character": "の", "romaji": "no", "type": "HIRAGANA", "line": 5},
    {"character": "は", "romaji": "ha", "type": "HIRAGANA", "line": 6},
    {"character": "ひ", "romaji": "hi", "type": "HIRAGANA", "line": 6},
    {"character": "ふ", "romaji": "fu", "type": "HIRAGANA", "line": 6},
    {"character": "へ", "romaji": "he", "type": "HIRAGANA", "line": 6},
    {"character": "ほ", "romaji": "ho", "type": "HIRAGANA", "line": 6},
    {"character": "ま", "romaji": "ma", "type": "HIRAGANA", "line": 7},
    {"character": "み", "romaji": "mi", "type": "HIRAGANA", "line": 7},
    {"character": "む", "romaji": "mu", "type": "HIRAGANA", "line": 7},
    {"character": "め", "romaji": "me", "type": "HIRAGANA", "line": 7},
    {"character": "も", "romaji": "mo", "type": "HIRAGANA", "line": 7},
    {"character": "や", "romaji": "ya", "type": "HIRAGANA", "line": 8},
    {"character": "ゆ", "romaji": "yu", "type": "HIRAGANA", "line": 8},
    {"character": "よ", "romaji": "yo", "type": "HIRAGANA", "line": 8},
    {"character": "ら", "romaji": "ra", "type": "HIRAGANA", "line": 9},
    {"character": "り", "romaji": "ri", "type": "HIRAGANA", "line": 9},
    {"character": "る", "romaji": "ru", "type": "HIRAGANA", "line": 9},
    {"character": "れ", "romaji": "re", "type": "HIRAGANA", "line": 9},
    {"character": "ろ", "romaji": "ro", "type": "HIRAGANA", "line": 9},
    {"character": "わ", "romaji": "wa", "type": "HIRAGANA", "line": 10},
    {"character": "を", "romaji": "wo", "type": "HIRAGANA", "line": 10},
    {"character": "ん", "romaji": "n", "type": "HIRAGANA", "line": 11},
    {"character": "が", "romaji": "ga", "type": "HIRAGANA", "line": 12},
    {"character": "ぎ", "romaji": "gi", "type": "HIRAGANA", "line": 12},
    {"character": "ぐ", "romaji": "gu", "type": "HIRAGANA", "line": 12},
    {"character": "げ", "romaji": "ge", "type": "HIRAGANA", "line": 12},
    {"character": "ご", "romaji": "go", "type": "HIRAGANA", "line": 12},
    {"character": "ざ", "romaji": "za", "type": "HIRAGANA", "line": 13},
    {"character": "じ", "romaji": "ji", "type": "HIRAGANA", "line": 13},
    {"character": "ず", "romaji": "zu", "type": "HIRAGANA", "line": 13},
    {"character": "ぜ", "romaji": "ze", "type": "HIRAGANA", "line": 13},
    {"character": "ぞ", "romaji": "zo", "type": "HIRAGANA", "line": 13},
    {"character": "だ", "romaji": "da", "type": "HIRAGANA", "line": 14},
    {"character": "ぢ", "romaji": "ji", "type": "HIRAGANA", "line": 14},
    {"character": "づ", "romaji": "zu", "type": "HIRAGANA", "line": 14},
    {"character": "で", "romaji": "de", "type": "HIRAGANA", "line": 14},
    {"character": "ど", "romaji": "do", "type": "HIRAGANA", "line": 14},
    {"character": "ば", "romaji": "ba", "type": "HIRAGANA", "line": 15},
    {"character": "び", "romaji": "bi", "type": "HIRAGANA", "line": 15},
    {"character": "ぶ", "romaji": "bu", "type": "HIRAGANA", "line": 15},
    {"character": "べ", "romaji": "be", "type": "HIRAGANA", "line": 15},
    {"character": "ぼ", "romaji": "bo", "type": "HIRAGANA", "line": 15},
    {"character": "ぱ", "romaji": "pa", "type": "HIRAGANA", "line": 16},
    {"character": "ぴ", "romaji": "pi", "type": "HIRAGANA", "line": 16},
    {"character": "ぷ", "romaji": "pu", "type": "HIRAGANA", "line": 16},
    {"character": "ぺ", "romaji": "pe", "type": "HIRAGANA", "line": 16},
    {"character": "ぽ", "romaji": "po", "type": "HIRAGANA", "line": 16},
    {"character": "きゃ", "romaji": "kya", "type": "HIRAGANA", "line": 17},
    {"character": "きゅ", "romaji": "kyu", "type": "HIRAGANA", "line": 17},
    {"character": "きょ", "romaji": "kyo", "type": "HIRAGANA", "line": 17},
    {"character": "しゃ", "romaji": "sha", "type": "HIRAGANA", "line": 18},
    {"character": "しゅ", "romaji": "shu", "type": "HIRAGANA", "line": 18},
    {"character": "しょ", "romaji": "sho", "type": "HIRAGANA", "line": 18},
    {"character": "ちゃ", "romaji": "cha", "type": "HIRAGANA", "line": 19},
    {"character": "ちゅ", "romaji": "chu", "type": "HIRAGANA", "line": 19},
    {"character": "ちょ", "romaji": "cho", "type": "HIRAGANA", "line": 19},
    {"character": "にゃ", "romaji": "nya", "type": "HIRAGANA", "line": 20},
    {"character": "にゅ", "romaji": "nyu", "type": "HIRAGANA", "line": 20},
    {"character": "にょ", "romaji": "nyo", "type": "HIRAGANA", "line": 20},
    {"character": "ひゃ", "romaji": "hya", "type": "HIRAGANA", "line": 21},
    {"character": "ひゅ", "romaji": "hyu", "type": "HIRAGANA", "line": 21},
    {"character": "ひょ", "romaji": "hyo", "type": "HIRAGANA", "line": 21},
    {"character": "みゃ", "romaji": "mya", "type": "HIRAGANA", "line": 22},
    {"character": "みゅ", "romaji": "myu", "type": "HIRAGANA", "line": 22},
    {"character": "みょ", "romaji": "myo", "type": "HIRAGANA", "line": 22},
    {"character": "りゃ", "romaji": "rya", "type": "HIRAGANA", "line": 23},
    {"character": "りゅ", "romaji": "ryu", "type": "HIRAGANA", "line": 23},
    {"character": "りょ", "romaji": "ryo", "type": "HIRAGANA", "line": 23},
    {"character": "ぎゃ", "romaji": "gya", "type": "HIRAGANA", "line": 24},
    {"character": "ぎゅ", "romaji": "gyu", "type": "HIRAGANA", "line": 24},
    {"character": "ぎょ", "romaji": "gyo", "type": "HIRAGANA", "line": 24},
    {"character": "じゃ", "romaji": "ja", "type": "HIRAGANA", "line": 25},
    {"character": "じゅ", "romaji": "ju", "type": "HIRAGANA", "line": 25},
    {"character": "じょ", "romaji": "jo", "type": "HIRAGANA", "line": 25},
    {"character": "ぢゃ", "romaji": "ja", "type": "HIRAGANA", "line": 26},
    {"character": "ぢゅ", "romaji": "ju", "type": "HIRAGANA", "line": 26},
    {"character": "ぢょ", "romaji": "jo", "type": "HIRAGANA", "line": 26},
    {"character": "びゃ", "romaji": "bya", "type": "HIRAGANA", "line": 27},
    {"character": "びゅ", "romaji": "byu", "type": "HIRAGANA", "line": 27},
    {"character": "びょ", "romaji": "byo", "type": "HIRAGANA", "line": 27},
    {"character": "ぴゃ", "romaji": "pya", "type": "HIRAGANA", "line": 28},
    {"character": "ぴゅ", "romaji": "pyu", "type": "HIRAGANA", "line": 28},
    {"character": "ぴょ", "romaji": "pyo", "type": "HIRAGANA", "line": 28}
  ]
}
"""

    private const val KATAKANA_JSON = """
{
  "characters": [
    {"character": "ア", "romaji": "a", "type": "KATAKANA", "line": 1},
    {"character": "イ", "romaji": "i", "type": "KATAKANA", "line": 1},
    {"character": "ウ", "romaji": "u", "type": "KATAKANA", "line": 1},
    {"character": "エ", "romaji": "e", "type": "KATAKANA", "line": 1},
    {"character": "オ", "romaji": "o", "type": "KATAKANA", "line": 1},
    {"character": "カ", "romaji": "ka", "type": "KATAKANA", "line": 2},
    {"character": "キ", "romaji": "ki", "type": "KATAKANA", "line": 2},
    {"character": "ク", "romaji": "ku", "type": "KATAKANA", "line": 2},
    {"character": "ケ", "romaji": "ke", "type": "KATAKANA", "line": 2},
    {"character": "コ", "romaji": "ko", "type": "KATAKANA", "line": 2},
    {"character": "サ", "romaji": "sa", "type": "KATAKANA", "line": 3},
    {"character": "シ", "romaji": "shi", "type": "KATAKANA", "line": 3},
    {"character": "ス", "romaji": "su", "type": "KATAKANA", "line": 3},
    {"character": "セ", "romaji": "se", "type": "KATAKANA", "line": 3},
    {"character": "ソ", "romaji": "so", "type": "KATAKANA", "line": 3},
    {"character": "タ", "romaji": "ta", "type": "KATAKANA", "line": 4},
    {"character": "チ", "romaji": "chi", "type": "KATAKANA", "line": 4},
    {"character": "ツ", "romaji": "tsu", "type": "KATAKANA", "line": 4},
    {"character": "テ", "romaji": "te", "type": "KATAKANA", "line": 4},
    {"character": "ト", "romaji": "to", "type": "KATAKANA", "line": 4},
    {"character": "ナ", "romaji": "na", "type": "KATAKANA", "line": 5},
    {"character": "ニ", "romaji": "ni", "type": "KATAKANA", "line": 5},
    {"character": "ヌ", "romaji": "nu", "type": "KATAKANA", "line": 5},
    {"character": "ネ", "romaji": "ne", "type": "KATAKANA", "line": 5},
    {"character": "ノ", "romaji": "no", "type": "KATAKANA", "line": 5},
    {"character": "ハ", "romaji": "ha", "type": "KATAKANA", "line": 6},
    {"character": "ヒ", "romaji": "hi", "type": "KATAKANA", "line": 6},
    {"character": "フ", "romaji": "fu", "type": "KATAKANA", "line": 6},
    {"character": "ヘ", "romaji": "he", "type": "KATAKANA", "line": 6},
    {"character": "ホ", "romaji": "ho", "type": "KATAKANA", "line": 6},
    {"character": "マ", "romaji": "ma", "type": "KATAKANA", "line": 7},
    {"character": "ミ", "romaji": "mi", "type": "KATAKANA", "line": 7},
    {"character": "ム", "romaji": "mu", "type": "KATAKANA", "line": 7},
    {"character": "メ", "romaji": "me", "type": "KATAKANA", "line": 7},
    {"character": "モ", "romaji": "mo", "type": "KATAKANA", "line": 7},
    {"character": "ヤ", "romaji": "ya", "type": "KATAKANA", "line": 8},
    {"character": "ユ", "romaji": "yu", "type": "KATAKANA", "line": 8},
    {"character": "ヨ", "romaji": "yo", "type": "KATAKANA", "line": 8},
    {"character": "ラ", "romaji": "ra", "type": "KATAKANA", "line": 9},
    {"character": "リ", "romaji": "ri", "type": "KATAKANA", "line": 9},
    {"character": "ル", "romaji": "ru", "type": "KATAKANA", "line": 9},
    {"character": "レ", "romaji": "re", "type": "KATAKANA", "line": 9},
    {"character": "ロ", "romaji": "ro", "type": "KATAKANA", "line": 9},
    {"character": "ワ", "romaji": "wa", "type": "KATAKANA", "line": 10},
    {"character": "ヲ", "romaji": "wo", "type": "KATAKANA", "line": 10},
    {"character": "ン", "romaji": "n", "type": "KATAKANA", "line": 11},
    {"character": "ガ", "romaji": "ga", "type": "KATAKANA", "line": 12},
    {"character": "ギ", "romaji": "gi", "type": "KATAKANA", "line": 12},
    {"character": "グ", "romaji": "gu", "type": "KATAKANA", "line": 12},
    {"character": "ゲ", "romaji": "ge", "type": "KATAKANA", "line": 12},
    {"character": "ゴ", "romaji": "go", "type": "KATAKANA", "line": 12},
    {"character": "ザ", "romaji": "za", "type": "KATAKANA", "line": 13},
    {"character": "ジ", "romaji": "ji", "type": "KATAKANA", "line": 13},
    {"character": "ズ", "romaji": "zu", "type": "KATAKANA", "line": 13},
    {"character": "ゼ", "romaji": "ze", "type": "KATAKANA", "line": 13},
    {"character": "ゾ", "romaji": "zo", "type": "KATAKANA", "line": 13},
    {"character": "ダ", "romaji": "da", "type": "KATAKANA", "line": 14},
    {"character": "ヂ", "romaji": "ji", "type": "KATAKANA", "line": 14},
    {"character": "ヅ", "romaji": "zu", "type": "KATAKANA", "line": 14},
    {"character": "デ", "romaji": "de", "type": "KATAKANA", "line": 14},
    {"character": "ド", "romaji": "do", "type": "KATAKANA", "line": 14},
    {"character": "バ", "romaji": "ba", "type": "KATAKANA", "line": 15},
    {"character": "ビ", "romaji": "bi", "type": "KATAKANA", "line": 15},
    {"character": "ブ", "romaji": "bu", "type": "KATAKANA", "line": 15},
    {"character": "ベ", "romaji": "be", "type": "KATAKANA", "line": 15},
    {"character": "ボ", "romaji": "bo", "type": "KATAKANA", "line": 15},
    {"character": "パ", "romaji": "pa", "type": "KATAKANA", "line": 16},
    {"character": "ピ", "romaji": "pi", "type": "KATAKANA", "line": 16},
    {"character": "プ", "romaji": "pu", "type": "KATAKANA", "line": 16},
    {"character": "ペ", "romaji": "pe", "type": "KATAKANA", "line": 16},
    {"character": "ポ", "romaji": "po", "type": "KATAKANA", "line": 16},
    {"character": "キャ", "romaji": "kya", "type": "KATAKANA", "line": 17},
    {"character": "キュ", "romaji": "kyu", "type": "KATAKANA", "line": 17},
    {"character": "キョ", "romaji": "kyo", "type": "KATAKANA", "line": 17},
    {"character": "シャ", "romaji": "sha", "type": "KATAKANA", "line": 18},
    {"character": "シュ", "romaji": "shu", "type": "KATAKANA", "line": 18},
    {"character": "ショ", "romaji": "sho", "type": "KATAKANA", "line": 18},
    {"character": "チャ", "romaji": "cha", "type": "KATAKANA", "line": 19},
    {"character": "チュ", "romaji": "chu", "type": "KATAKANA", "line": 19},
    {"character": "チョ", "romaji": "cho", "type": "KATAKANA", "line": 19},
    {"character": "ニャ", "romaji": "nya", "type": "KATAKANA", "line": 20},
    {"character": "ニュ", "romaji": "nyu", "type": "KATAKANA", "line": 20},
    {"character": "ニョ", "romaji": "nyo", "type": "KATAKANA", "line": 20},
    {"character": "ヒャ", "romaji": "hya", "type": "KATAKANA", "line": 21},
    {"character": "ヒュ", "romaji": "hyu", "type": "KATAKANA", "line": 21},
    {"character": "ヒョ", "romaji": "hyo", "type": "KATAKANA", "line": 21},
    {"character": "ミャ", "romaji": "mya", "type": "KATAKANA", "line": 22},
    {"character": "ミュ", "romaji": "myu", "type": "KATAKANA", "line": 22},
    {"character": "ミョ", "romaji": "myo", "type": "KATAKANA", "line": 22},
    {"character": "リャ", "romaji": "rya", "type": "KATAKANA", "line": 23},
    {"character": "リュ", "romaji": "ryu", "type": "KATAKANA", "line": 23},
    {"character": "リョ", "romaji": "ryo", "type": "KATAKANA", "line": 23},
    {"character": "ギャ", "romaji": "gya", "type": "KATAKANA", "line": 24},
    {"character": "ギュ", "romaji": "gyu", "type": "KATAKANA", "line": 24},
    {"character": "ギョ", "romaji": "gyo", "type": "KATAKANA", "line": 24},
    {"character": "ジャ", "romaji": "ja", "type": "KATAKANA", "line": 25},
    {"character": "ジュ", "romaji": "ju", "type": "KATAKANA", "line": 25},
    {"character": "ジョ", "romaji": "jo", "type": "KATAKANA", "line": 25},
    {"character": "ヂャ", "romaji": "ja", "type": "KATAKANA", "line": 26},
    {"character": "ヂュ", "romaji": "ju", "type": "KATAKANA", "line": 26},
    {"character": "ヂョ", "romaji": "jo", "type": "KATAKANA", "line": 26},
    {"character": "ビャ", "romaji": "bya", "type": "KATAKANA", "line": 27},
    {"character": "ビュ", "romaji": "byu", "type": "KATAKANA", "line": 27},
    {"character": "ビョ", "romaji": "byo", "type": "KATAKANA", "line": 27},
    {"character": "ピャ", "romaji": "pya", "type": "KATAKANA", "line": 28},
    {"character": "ピュ", "romaji": "pyu", "type": "KATAKANA", "line": 28},
    {"character": "ピョ", "romaji": "pyo", "type": "KATAKANA", "line": 28}
  ]
}
"""
}
